server:
  port: 8080

spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/ssm1?serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      enabled: true
      max-file-size: 3MB
      max-request-size: 3MB

mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: pers.ssm.po


